// <auto-generated />
using System;
using Demergenza.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Demergenza.Persistence.Migrations
{
    [DbContext(typeof(DemergenzaDbContext))]
    [Migration("20240107232642_mig5")]
    partial class mig5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("main")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Demergenza.Domain.Entities.Admin.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(48)")
                        .HasColumnName("fullName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("tbl_admin", "main");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.Menu.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(48)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("tbl_category", "main");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.Menu.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("image");

                    b.Property<string>("Ingredients")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Ingredients");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(48)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CategoryId");

                    b.ToTable("tbl_menu", "main");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.PageContents.AboutUs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("image");

                    b.Property<string>("TextContent")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("text-content");

                    b.HasKey("Id");

                    b.ToTable("tbl_about_us", "main");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.PageContents.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("address");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("phone");

                    b.Property<string>("SecondPhone")
                        .HasColumnType("varchar(24)")
                        .HasColumnName("second-phone");

                    b.HasKey("Id");

                    b.ToTable("tbl_contact", "main");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.PageContents.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alt")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("alt");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("image-src");

                    b.Property<string>("ImageWidth")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("image-width");

                    b.Property<string>("Subtitle")
                        .HasColumnType("varchar(600)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("title");

                    b.Property<string>("TitleSrc")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("title-src");

                    b.Property<string>("Top")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("top");

                    b.HasKey("Id");

                    b.ToTable("tbl_hero", "main");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.Menu.Category", b =>
                {
                    b.HasOne("Demergenza.Domain.Entities.Admin.Admin", "Admin")
                        .WithMany("TblCategories")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.Menu.Menu", b =>
                {
                    b.HasOne("Demergenza.Domain.Entities.Admin.Admin", "Admin")
                        .WithMany("TblMenus")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demergenza.Domain.Entities.Menu.Category", "Category")
                        .WithMany("Menus")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.Admin.Admin", b =>
                {
                    b.Navigation("TblCategories");

                    b.Navigation("TblMenus");
                });

            modelBuilder.Entity("Demergenza.Domain.Entities.Menu.Category", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
